language: python

arch:
  - arm64

services:
  - docker

install: skip

script:
  - echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
  - export REPOSITORY=piikki-cache-api
  - export IMAGE_TAG=latest
  - sh push-api.sh
  - export REPOSITORY=piikki-tg-bot
  - sh push-tg-bot.sh
