export default {
  'Helsingin ja Uudenmaan SHP': 'HYKS',
  'Etelä-Karjalan SHP': 'HYKS',
  'Kymenlaakson SHP': 'HYKS',
  'Päijät-Hämeen SHP': 'HYKS',
  'Pohjois-Savon SHP': 'KYS',
  'Etelä-Savon SHP': 'KYS',
  'Itä-Savon SHP': 'KYS',
  'Keski-Suomen SHP': 'KYS',
  'Pohjois-Karjalan SHP': 'OYS',
  'Pohjois-Pohjanmaan SHP': 'OYS',
  'Kainuun SHP': 'OYS',
  'Keski-Pohjanmaan SHP': 'OYS',
  'Lapin SHP': 'OYS',
  'Länsi-Pohjan SHP': 'OYS',
  'Pirkanmaan SHP': 'TAYS',
  'Etelä-Pohjanmaan SHP': 'TAYS',
  'Kanta-Hämeen SHP': 'TAYS',
  'Varsinais-Suomen SHP': 'TYKS',
  'Satakunnan SHP': 'TYKS',
  'Vaasan SHP': 'TYKS',
  Ahvenanmaa: 'Ahvenanmaa',
}
