name: build-and-push

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build docker image
        env:
          ECR_URL: ${{ secrets.ECR_URL }}
        run: docker build -f ./sync/Dockerfile -t $ECR_URL/piikki-sync:latest .

      - name: Push image
        env:
          ECR_URL: ${{ secrets.ECR_URL }}
        run: docker push $ECR_URL/piikki-sync:latest
